title: Pengcheng Ding # your name (or website title) here
logo: "/images/circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am currently getting my PhD from Johns Hopkins University. My research area is electricity market. I build game theory based optimization models to simulate how different market players respond to different policies and market prices for policy recommendation.
  Extracting insights from mathematical models for real-world decision making has been passion for the past few years. I believe data science is the field where I can combine my skills and my passion to help inform better decisions. This belief has driven to join the Insight program as
  an Insight Fellow, where I furthered my understanding of machine learning and helped a company to develop its first keyphrase extraction pipeline. This experience has solidified my understanding of machine learning and made me determined to seek a career as a Data Scientist.
  <br><br>
  <a href="https://github.com/pchding/aboutme/blob/master/pdf/PengchengDing_Resume.pdf">View My Resume</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal